-- ============================================================
-- Migration 024 - Cafe Locco menu seed (genuine Figma menu)
-- Source of truth: figma-reference/src/app/components/MenuPage.tsx
-- Replaces placeholder items from migration 023. Idempotent.
-- ============================================================

delete from public.menu_items;

insert into public.menu_items
  (name, description, price, category, is_available, is_featured)
values
  ('LOCCO BREAKFAST', 'Two free-range eggs any style, two turkey rashers, lamb sausage, baked beans, garlic mushrooms, roasted tomato, hash brown, and choice of toast.', 13.49, 'breakfast', true, false),
  ('TRADITIONAL DESI BREAKFAST', 'Two free-range eggs any style, house keema, masala chaats, spiced beans, roasted tomato, and choice of paratha or puri.', 13.49, 'breakfast', true, false),
  ('VEGGIE BREAKFAST', 'Two free-range eggs any style, veggie sausages, baked beans, garlic mushrooms, roasted tomato, hash brown, and choice of toast.', 13.49, 'breakfast', true, false),
  ('VEGAN BREAKFAST', 'Vegan scrambled eggs, veggie sausages, smashed avocado, baked beans, garlic mushrooms, roasted tomato, hash brown, and choice of toast.', 13.49, 'breakfast', true, false),
  ('GLUTEN-FREE BREAKFAST', 'Two free-range eggs any style, two turkey rashers, lamb sausage, baked beans, garlic mushrooms, roasted tomato, and hash brown.', 13.49, 'breakfast', true, false),
  ('AVO TOAST', 'Smashed avocado, two poached eggs, chilli flakes, edamame beans, on choice of toast.', 12.99, 'classics', true, false),
  ('TUNACADO', 'Tuna mixed with spices, smashed avocado, two poached eggs, on choice of toast.', 13.49, 'classics', true, false),
  ('MUSHROOM AVO', 'Smashed avocado, sautéed garlic mushrooms, two poached eggs, on choice of toast.', 13.49, 'classics', true, false),
  ('THE ROYALE', 'Two poached eggs, turkey rashers, hollandaise sauce, on an English muffin.', 13.99, 'classics', true, false),
  ('CHILLI-GARLIC FLORENTINE', 'Two poached eggs, garlic and chilli spinach, hollandaise sauce, on an English muffin.', 13.99, 'classics', true, false),
  ('SWEET & SOUR CRISPY CHICKEN', 'Buttermilk marinated crispy chicken strips, topped with our house sweet and sour sauce on choice of toast.', 13.99, 'classics', true, false),
  ('SPICE ME UP SCRAMBLED', 'Chilli scrambled eggs, topped with spiced masala sauce on choice of toast.', 12.49, 'classics', true, false),
  ('NUTTY SHAKSHUKA', 'Two eggs poached in a tomato and pepper stew with a hint of peanut butter, served with choice of toast.', 13.49, 'classics', true, false),
  ('HUEVOS RANCHEROS', 'Two fried eggs, black beans, avocado, salsa, sour cream, on corn tortillas.', 13.99, 'classics', true, false),
  ('BUFFALO WINGS', 'Marinated chicken wings tossed in buffalo sauce, served with sour cream.', 9.49, 'appetisers', true, false),
  ('HALLOUMI FRIES', 'Deep fried halloumi strips served with sweet chilli sauce.', 8.99, 'appetisers', true, false),
  ('DYNAMITE PRAWNS', 'Panko breaded prawns tossed in dynamite sauce.', 9.99, 'appetisers', true, false),
  ('POPPIN POPPERS', 'Jalapeño peppers stuffed with cream cheese, deep fried and served with sour cream.', 8.49, 'appetisers', true, false),
  ('CALAMARI', 'Deep fried squid rings served with sweet chilli sauce and lemon wedge.', 9.49, 'appetisers', true, false),
  ('LOADED FRIES', 'Crispy fries loaded with melted cheese, jalapeños, and sour cream.', 7.99, 'appetisers', true, false),
  ('KOREAN BBQ BOWL', 'Korean BBQ chicken, edamame beans, red cabbage, sweetcorn, crispy onions, sesame seeds, on a bed of rice.', 14.49, 'bowls', true, false),
  ('TERIYAKI SALMON BOWL', 'Teriyaki glazed salmon, edamame beans, red cabbage, sweetcorn, sesame seeds, on a bed of rice.', 15.99, 'bowls', true, false),
  ('FALAFEL BOWL', 'Falafels, hummus, mixed leaves, red cabbage, sweetcorn, red onion, on a bed of quinoa.', 13.49, 'bowls', true, false),
  ('PERI PERI CHICKEN BOWL', 'Peri peri chicken, mixed peppers, red onion, sweetcorn, on a bed of rice.', 14.49, 'bowls', true, false),
  ('FISH & CHIPS', 'Beer battered cod served with chips, mushy peas, and tartar sauce.', 16.99, 'favourites', true, false),
  ('CHICKEN & WAFFLES', 'Crispy chicken strips on Belgian waffles, drizzled with maple syrup.', 15.49, 'favourites', true, false),
  ('MAC & CHEESE', 'Creamy macaroni cheese topped with breadcrumbs.', 12.99, 'favourites', true, false),
  ('STEAK & FRIES', 'Grilled ribeye steak served with chips and peppercorn sauce.', 22.99, 'favourites', true, false),
  ('LOCCO BURGER', 'Beef patty, cheese, lettuce, tomato, pickles, LOCCO sauce, in a brioche bun.', 14.99, 'burgers', true, false),
  ('BUTTERMILK CHICKEN BURGER', 'Buttermilk fried chicken, lettuce, tomato, mayo, in a brioche bun.', 14.49, 'burgers', true, false),
  ('HALLOUMI BURGER', 'Grilled halloumi, roasted peppers, lettuce, pesto mayo, in a brioche bun.', 13.99, 'burgers', true, false),
  ('BEYOND BURGER', 'Plant-based patty, vegan cheese, lettuce, tomato, vegan mayo, in a vegan bun.', 14.99, 'burgers', true, false),
  ('BBQ BACON BURGER', 'Beef patty, turkey bacon, cheese, onion rings, BBQ sauce, in a brioche bun.', 15.99, 'burgers', true, false),
  ('CHICKEN CAESAR WRAP', 'Grilled chicken, lettuce, parmesan, Caesar dressing, in a tortilla wrap.', 11.99, 'wraps', true, false),
  ('FALAFEL WRAP', 'Falafels, hummus, lettuce, tomato, red onion, in a tortilla wrap.', 10.99, 'wraps', true, false),
  ('PERI PERI CHICKEN WRAP', 'Peri peri chicken, lettuce, tomato, mayo, in a tortilla wrap.', 11.99, 'wraps', true, false),
  ('HALLOUMI WRAP', 'Grilled halloumi, roasted peppers, lettuce, pesto mayo, in a tortilla wrap.', 10.99, 'wraps', true, false),
  ('KIDS PANCAKES', 'Fluffy pancakes with maple syrup and berries.', 6.99, 'kids', true, false),
  ('KIDS CHICKEN NUGGETS', 'Crispy chicken nuggets with chips.', 7.99, 'kids', true, false),
  ('KIDS FISH FINGERS', 'Fish fingers with chips.', 7.99, 'kids', true, false),
  ('KIDS MAC & CHEESE', 'Creamy macaroni cheese.', 6.99, 'kids', true, false),
  ('KIDS BURGER', 'Mini beef burger with chips.', 8.49, 'kids', true, false),
  ('CHIPS', null, 4.49, 'sides', true, false),
  ('SWEET POTATO FRIES', null, 4.99, 'sides', true, false),
  ('ONION RINGS', null, 4.49, 'sides', true, false),
  ('GARLIC BREAD', null, 3.99, 'sides', true, false),
  ('SIDE SALAD', null, 3.99, 'sides', true, false),
  ('COLESLAW', null, 2.99, 'sides', true, false),
  ('PANCAKE STACK', 'Fluffy pancakes with maple syrup, berries, and whipped cream.', 10.99, 'sweets', true, false),
  ('FRENCH TOAST', 'Brioche French toast with caramelized bananas and maple syrup.', 10.99, 'sweets', true, false),
  ('WAFFLES', 'Belgian waffles with Nutella, strawberries, and ice cream.', 11.49, 'sweets', true, false),
  ('BROWNIE SUNDAE', 'Warm chocolate brownie with vanilla ice cream and chocolate sauce.', 8.99, 'sweets', true, false),
  ('CHEESECAKE', 'Baked vanilla cheesecake with berry compote.', 7.99, 'sweets', true, false),
  ('ESPRESSO', null, 2.99, 'drinks', true, false),
  ('AMERICANO', null, 3.49, 'drinks', true, false),
  ('CAPPUCCINO', null, 3.99, 'drinks', true, false),
  ('LATTE', null, 3.99, 'drinks', true, false),
  ('FLAT WHITE', null, 3.99, 'drinks', true, false),
  ('MOCHA', null, 4.49, 'drinks', true, false),
  ('HOT CHOCOLATE', null, 3.99, 'drinks', true, false),
  ('TEA', null, 2.99, 'drinks', true, false),
  ('ICED LATTE', null, 4.49, 'drinks', true, false),
  ('ICED AMERICANO', null, 3.99, 'drinks', true, false),
  ('COCA-COLA', null, 3.49, 'soft-drinks', true, false),
  ('DIET COKE', null, 3.49, 'soft-drinks', true, false),
  ('SPRITE', null, 3.49, 'soft-drinks', true, false),
  ('FANTA', null, 3.49, 'soft-drinks', true, false),
  ('ORANGE JUICE', null, 3.99, 'soft-drinks', true, false),
  ('APPLE JUICE', null, 3.99, 'soft-drinks', true, false),
  ('STILL WATER', null, 2.49, 'soft-drinks', true, false),
  ('SPARKLING WATER', null, 2.49, 'soft-drinks', true, false),
  ('VIRGIN MOJITO', null, 10, 'mocktails', true, false),
  ('STRAWBERRY DAIQUIRI', null, 10, 'mocktails', true, false),
  ('PINA COLADA', null, 10, 'mocktails', true, false),
  ('COCO COLADA', null, 10, 'mocktails', true, false),
  ('MANGO LASSI', null, 10, 'mocktails', true, false),
  ('MANGO, GINGER AND LYCHEE COOLER', null, 10, 'mocktails', true, false),
  ('OCEAN WAVE', null, 10, 'mocktails', true, false),
  ('WHITE WHISPER', null, 10, 'mocktails', true, false),
  ('KIWI SPRITZ', null, 10, 'mocktails', true, false),
  ('LOCCO PUNCH', null, 12, 'mocktails', true, false);
