-- 027: add a human-friendly booking reference to reservations.
-- The reference (e.g. "CL-W647KN") is generated by the app at submission time,
-- shown to the guest on the success screen, stored here for the restaurant, and
-- included in the notify-submission email so staff can quote it when they call
-- the guest to confirm the booking.

alter table public.reservations
  add column if not exists reference text;

comment on column public.reservations.reference is
  'Human-friendly booking reference shown to the guest (e.g. CL-W647KN).';

create index if not exists reservations_reference_idx
  on public.reservations(reference);
